name: build_docker

on:
  workflow_dispatch:

jobs:
  build_docker:
    name: 构建 Docker 镜像
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 获取当前日期
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        if: github.event_name != 'pull_request'

      - name: 缓存依赖项
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        if: github.event_name != 'pull_request'

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2
        if: github.event_name != 'pull_request'

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: github.event_name != 'pull_request'

      - name: 登录 DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: 构建并推送
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/btpanel:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/btpanel:npm-${{ steps.date.outputs.today }}
          platforms: linux/amd64
